export enum EnumStep {
  UPLOAD = 'UPLOAD',
  TRANSCRIBE = 'TRANSCRIBE',
  LOADING = 'LOADING',
  TRANSCRIPT = 'TRANSCRIPT',
  GENERATING = 'GENERATING',
  HISTORY = 'HISTORY',
  DONE = 'DONE',
  FINISH = 'FINISH',
  ALL = 'ALL',
}
